package dk.trustworks.intranet.recruitmentservice.domain.enums;

public enum OutboxKind {
    SLACK_DM, SLACK_CHANNEL_DIGEST,
    OUTLOOK_EVENT_CREATE, OUTLOOK_EVENT_UPDATE, OUTLOOK_EVENT_CANCEL,
    SHAREPOINT_PROVISION_CANDIDATE_FOLDER, SHAREPOINT_ARCHIVE_SIGNED_CONTRACT,
    SHAREPOINT_CONVERT_CANDIDATE_FOLDER, SHAREPOINT_DELETE_CANDIDATE_FOLDER,
    NEXTSIGN_CREATE_CASE, NEXTSIGN_RECONCILE_CASE,
    REVIEW_EMAIL_SEND, RETENTION_WARNING_EMAIL, RETENTION_ANONYMIZE_CANDIDATE,
    AI_GENERATE
}
