package dk.trustworks.intranet.recruitmentservice.ai;

import dk.trustworks.intranet.apis.openai.OpenAIService;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventBuilder;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventRecorder;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventType;
import dk.trustworks.intranet.recruitmentservice.services.RecruitmentAiFeatureFlag;
import dk.trustworks.intranet.recruitmentservice.services.RecruitmentFeatureFlag;
import io.quarkus.narayana.jta.QuarkusTransaction;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import lombok.extern.jbosslog.JBossLog;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.ZoneId;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The two P24 AI digests (AI spec §5.5, plan §P24): the weekly funnel
 * narrative for the recruitment Slack channel and the quarterly
 * rejection-pattern narrative feeding direktionens sourcing report. This
 * service GENERATES a digest and appends {@code AI_DIGEST_GENERATED}; the
 * Slack posting is downstream ({@code SlackDigestRenderer} consumes the
 * event) — generation and delivery are decoupled exactly like every other
 * reactor moment.
 *
 * <h3>The PII boundary, three layers deep</h3>
 * Model input is exclusively the P20 reporting projection's aggregates
 * (plus bare open-position counts) carried by {@link AiDigestFacts} —
 * numbers and enum codes by type system; the projection's schema cannot
 * hold names; and the digest event stores its narrative in
 * {@code payload} (not {@code pii}) precisely BECAUSE it contains
 * aggregates only, so digests survive anonymization sweeps unchanged —
 * the one deliberate inversion of the pii rule (plan §P24, findings §P9).
 *
 * <h3>Cadence &amp; idempotency — self-healing clock</h3>
 * The digest batchlet runs DAILY; each digest decides for itself whether
 * its period needs generating (event-derived, the P17/P23 idiom):
 * <ul>
 *   <li><b>Weekly:</b> one digest per ISO week — generated by the first
 *       run of the week (normally Monday 06:30 UTC); a failed Monday run
 *       (OpenAI outage) retries Tuesday, keyed on the same week.</li>
 *   <li><b>Quarterly:</b> one digest per just-ended <em>fiscal</em>
 *       quarter (July→June year), generated within the first
 *       {@link #REJECTION_GRACE_DAYS} days of the new quarter. Enabling
 *       the toggle after the window ⇒ no retroactive digest (the
 *       companion specs' no-backfill rule).</li>
 * </ul>
 * Two instances racing on the same period (ECS cutover) can both
 * generate — at worst one duplicate digest, the morning-brief posture.
 *
 * <h3>Gating</h3>
 * {@code recruitment.pipeline.enabled} (the P22/P23 precedent — no side
 * surface leaks a dark module's activity) AND the digest's own
 * {@code recruitment.ai.digest.*} toggle, both read fresh per run.
 * OpenAI calls run with no transaction active and {@code store=false}
 * (the module's standing posture) — and the input is numbers anyway.
 */
@JBossLog
@ApplicationScoped
public class AiDigestService {

    /** payload.kind of the weekly funnel digest. */
    public static final String KIND_WEEKLY_FUNNEL = "WEEKLY_FUNNEL";

    /** payload.kind of the quarterly rejection-pattern digest. */
    public static final String KIND_REJECTION_PATTERNS = "REJECTION_PATTERNS";

    /** The quarterly digest generates only this many days into the new quarter. */
    static final int REJECTION_GRACE_DAYS = 14;

    /**
     * TREND window only: the current month (month-to-date) plus this many
     * full months back. This is <b>not</b> the digest's reported period —
     * that is the single ISO week named by {@link #isoWeekKey}. The two
     * were the same field until 2026-08-22, which is why a message headed
     * "week 34" reported four months of numbers and its prose opened
     * "I denne måned".
     */
    static final int WEEKLY_WINDOW_MONTHS_BACK = 3;

    /** Narratives are a short paragraph; cap the stored text defensively. */
    static final int NARRATIVE_MAX_LENGTH = 6000;

    /** ~4-8 Danish sentences; generous without letting a runaway response spin. */
    static final int MAX_OUTPUT_TOKENS = 900;

    /** Natural prose wants temperature (the P16 draft-model reasoning). */
    static final double TEMPERATURE = 0.7;

    /** The digest clock runs on the Copenhagen calendar (the P23 idiom). */
    public static final ZoneId COPENHAGEN = ZoneId.of("Europe/Copenhagen");

    /**
     * The digests reuse the P16 draft model config: both need a
     * temperature-capable model for natural Danish prose, and a second
     * config knob for the same requirement would just drift.
     */
    @ConfigProperty(name = "dk.trustworks.recruitment.ai.draft-model", defaultValue = "gpt-4o-mini")
    String digestModel;

    @Inject
    OpenAIService openAIService;

    @Inject
    RecruitmentFeatureFlag featureFlag;

    @Inject
    RecruitmentAiFeatureFlag aiFlags;

    @Inject
    RecruitmentEventRecorder eventRecorder;

    /**
     * Read-only here: the digest asks it which practices have a channel of
     * their own, so a practice only gets its own edition when there is
     * somewhere to post it. Delivery itself stays in
     * {@code SlackDigestRenderer}.
     */
    @Inject
    dk.trustworks.intranet.recruitmentservice.notifications.RecruitmentSlackChannelRouter
            channelRouter;

    @Inject
    EntityManager em;

    /** Result of one digest attempt, for logs and the batchlet exit status. */
    public record DigestSummary(String kind, boolean enabled, boolean generated, String period) {

        @Override
        public String toString() {
            if (!enabled) {
                return kind + "[disabled]";
            }
            return kind + "[" + (generated ? "generated " : "up-to-date ") + period + "]";
        }
    }

    // ------------------------------------------------------------------
    // Weekly funnel narrative
    // ------------------------------------------------------------------

    /**
     * Generate this ISO week's funnel digest when it does not exist yet.
     * Safe to call daily and concurrently (class javadoc).
     */
    public DigestSummary runWeeklyFunnel() {
        return runWeeklyFunnel(LocalDate.now(COPENHAGEN));
    }

    /**
     * Clock-injected variant — the batchlet passes today; tests pass fixed
     * dates. Generates the company-wide digest (posted to the HR channel)
     * and then one digest per practice that has its own Slack channel, so
     * each practice reads its own funnel instead of the whole company's
     * (decided 2026-08-12). The returned summary is the company-wide one;
     * per-practice outcomes are logged.
     */
    public DigestSummary runWeeklyFunnel(LocalDate today) {
        DigestSummary companyWide = runWeeklyFunnel(today, null);
        if (companyWide.enabled()) {
            YearMonth windowTo = YearMonth.from(today);
            for (String practiceUuid : inTx(() -> practicesWithOwnChannel(
                    windowTo.minusMonths(WEEKLY_WINDOW_MONTHS_BACK), windowTo))) {
                log.infof("AI digest per-practice: %s", runWeeklyFunnel(today, practiceUuid));
            }
        }
        return companyWide;
    }

    /** One weekly digest: company-wide when {@code practiceUuid} is null. */
    private DigestSummary runWeeklyFunnel(LocalDate today, String practiceUuid) {
        if (!inTx(featureFlag::isPipelineEnabled) || !inTx(aiFlags::isWeeklyFunnelDigestEnabled)) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, false, false, null);
        }
        String period = isoWeekKey(today);
        if (inTx(() -> digestExists(KIND_WEEKLY_FUNNEL, period, practiceUuid))) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, true, false, period);
        }
        // The reported period is the ISO week `period` names — not the
        // trend window. Conflating the two is what made a message headed
        // "week 34" report four months of numbers.
        LocalDate weekMonday = today.with(WeekFields.ISO.dayOfWeek(), 1L);
        YearMonth windowTo = YearMonth.from(today);
        YearMonth windowFrom = windowTo.minusMonths(WEEKLY_WINDOW_MONTHS_BACK);
        AiDigestFacts facts =
                inTx(() -> loadWeeklyFacts(weekMonday, windowFrom, windowTo, practiceUuid));

        String narrative = callModel(AiDigestPrompts.weeklySystemPrompt(),
                AiDigestPrompts.weeklyUserPrompt(facts), KIND_WEEKLY_FUNNEL, period);
        if (narrative == null) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, true, false, period);
        }

        // Every KPI is week-scoped and carries its own delta, so the
        // renderer never has to choose a window and the reader can tell up
        // from down. `open_positions` is current state and has no delta.
        AiDigestFacts.FunnelWindow week = facts.weeklyFunnel().week();
        AiDigestFacts.FunnelWindow prev = facts.weeklyFunnel().previousWeek();
        Map<String, Object> kpis = new LinkedHashMap<>();
        kpis.put("applications", week.applicationTotal());
        kpis.put("applications_delta", week.applicationTotal() - prev.applicationTotal());
        kpis.put("stage_moves", week.stageMoveTotal());
        kpis.put("stage_moves_delta", week.stageMoveTotal() - prev.stageMoveTotal());
        kpis.put("terminals", week.terminalTotal());
        kpis.put("terminals_delta", week.terminalTotal() - prev.terminalTotal());
        kpis.put("hires", week.hires());
        kpis.put("hires_delta", week.hires() - prev.hires());
        kpis.put("scorecards", week.scorecardsSubmitted());
        kpis.put("scorecards_delta", week.scorecardsSubmitted() - prev.scorecardsSubmitted());
        kpis.put("nudges", week.nudgeTotal());
        kpis.put("nudges_delta", week.nudgeTotal() - prev.nudgeTotal());
        kpis.put("open_positions", facts.weeklyFunnel().openPositions());

        inTx(() -> {
            appendDigestEvent(KIND_WEEKLY_FUNNEL, period, facts, narrative, kpis, practiceUuid);
            return null;
        });
        log.infof("AI_DIGEST_GENERATED kind=%s period=%s practice=%s model=%s",
                KIND_WEEKLY_FUNNEL, period, practiceUuid == null ? "ALL" : practiceUuid, digestModel);
        return new DigestSummary(KIND_WEEKLY_FUNNEL, true, true, period);
    }

    // ------------------------------------------------------------------
    // Quarterly rejection patterns
    // ------------------------------------------------------------------

    /**
     * Generate the just-ended fiscal quarter's rejection digest when
     * inside the grace window and not generated yet.
     */
    public DigestSummary runRejectionPatterns() {
        return runRejectionPatterns(LocalDate.now(COPENHAGEN));
    }

    /**
     * Clock-injected variant — the batchlet passes today; tests pass fixed
     * dates. Like the weekly digest: one company-wide edition for the HR
     * channel plus one per practice that has its own channel.
     */
    public DigestSummary runRejectionPatterns(LocalDate today) {
        DigestSummary companyWide = runRejectionPatterns(today, null);
        if (companyWide.enabled() && companyWide.period() != null) {
            YearMonth quarterStart = fiscalQuarterStart(YearMonth.from(today));
            for (String practiceUuid : inTx(() -> practicesWithOwnChannel(
                    quarterStart.minusMonths(3), quarterStart.minusMonths(1)))) {
                log.infof("AI digest per-practice: %s", runRejectionPatterns(today, practiceUuid));
            }
        }
        return companyWide;
    }

    /** One quarterly digest: company-wide when {@code practiceUuid} is null. */
    private DigestSummary runRejectionPatterns(LocalDate today, String practiceUuid) {
        if (!inTx(featureFlag::isPipelineEnabled) || !inTx(aiFlags::isRejectionPatternsDigestEnabled)) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, false, false, null);
        }
        YearMonth quarterStart = fiscalQuarterStart(YearMonth.from(today));
        if (today.isAfter(quarterStart.atDay(1).plusDays(REJECTION_GRACE_DAYS - 1L))) {
            // Outside the window — the ended quarter's digest either exists
            // or was deliberately never generated (no retroactive backfill).
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, null);
        }
        YearMonth windowFrom = quarterStart.minusMonths(3);
        YearMonth windowTo = quarterStart.minusMonths(1);
        String period = fiscalQuarterLabel(windowFrom);
        if (inTx(() -> digestExists(KIND_REJECTION_PATTERNS, period, practiceUuid))) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, period);
        }
        AiDigestFacts facts = inTx(() ->
                loadRejectionFacts(windowFrom, windowTo, period, practiceUuid));

        String narrative = callModel(AiDigestPrompts.rejectionSystemPrompt(),
                AiDigestPrompts.rejectionUserPrompt(facts), KIND_REJECTION_PATTERNS, period);
        if (narrative == null) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, period);
        }

        Map<String, Object> kpis = new LinkedHashMap<>();
        kpis.put("rejections", facts.rejectionPatterns().totalRejections());
        kpis.put("applications", facts.rejectionPatterns().totalApplications());

        inTx(() -> {
            appendDigestEvent(KIND_REJECTION_PATTERNS, period, facts, narrative, kpis, practiceUuid);
            return null;
        });
        log.infof("AI_DIGEST_GENERATED kind=%s period=%s practice=%s model=%s",
                KIND_REJECTION_PATTERNS, period, practiceUuid == null ? "ALL" : practiceUuid,
                digestModel);
        return new DigestSummary(KIND_REJECTION_PATTERNS, true, true, period);
    }

    /**
     * The practices that get their own digest: those with activity in the
     * window AND a configured Slack channel of their own. A practice with no
     * channel is deliberately skipped rather than routed to the default —
     * six near-identical digests in one shared channel is noise, and the
     * company-wide edition already covers them. Partner-track rows never
     * qualify a practice (they are excluded from per-practice digests
     * entirely, see {@link #practiceScope}).
     */
    @SuppressWarnings("unchecked")
    private List<String> practicesWithOwnChannel(YearMonth from, YearMonth to) {
        List<String> active = em.createNativeQuery("""
                        SELECT DISTINCT practice_uuid
                        FROM recruitment_fact_monthly
                        WHERE month BETWEEN :f AND :t
                          AND practice_uuid <> '' AND hiring_track <> 'PARTNER'
                        ORDER BY 1
                        """)
                .setParameter("f", from.atDay(1))
                .setParameter("t", to.atDay(1))
                .getResultList();
        return active.stream()
                .filter(uuid -> channelRouter.practiceChannel(uuid).isPresent())
                .toList();
    }

    // ------------------------------------------------------------------
    // Period keys (fiscal year July→June — docs/finalized/shared/fiscal-year.md)
    // ------------------------------------------------------------------

    /** ISO week key, e.g. {@code 2026-W30} (week-based year). Shared with the DPO digest. */
    public static String isoWeekKey(LocalDate date) {
        int week = date.get(WeekFields.ISO.weekOfWeekBasedYear());
        int year = date.get(WeekFields.ISO.weekBasedYear());
        return "%d-W%02d".formatted(year, week);
    }

    /** First month of the fiscal quarter containing the given month (Jul/Oct/Jan/Apr). */
    static YearMonth fiscalQuarterStart(YearMonth month) {
        int offset = (month.getMonthValue() - 7 + 12) % 3;
        return month.minusMonths(offset);
    }

    /**
     * Fiscal-quarter period key of the quarter STARTING at the given month,
     * e.g. {@code 2026-04} → {@code FY2025/26-Q4}.
     */
    static String fiscalQuarterLabel(YearMonth quarterStart) {
        int m = quarterStart.getMonthValue();
        int fyStartYear = m >= 7 ? quarterStart.getYear() : quarterStart.getYear() - 1;
        int quarter = switch (m) {
            case 7 -> 1;
            case 10 -> 2;
            case 1 -> 3;
            case 4 -> 4;
            default -> throw new IllegalArgumentException(
                    quarterStart + " is not a fiscal quarter start");
        };
        return "FY%d/%02d-Q%d".formatted(fyStartYear, (fyStartYear + 1) % 100, quarter);
    }

    // ------------------------------------------------------------------
    // Idempotency (event-derived)
    // ------------------------------------------------------------------

    /**
     * Idempotency is per (kind, period, practice): the company-wide edition
     * and each practice's edition of the same week are separate digests, so
     * generating one must not suppress the others. Company-wide events carry
     * no {@code practice_uuid}, hence the COALESCE to the '' sentinel — that
     * also keeps digests written before 2026-08-12 matching the company-wide
     * key, so no historical week is regenerated.
     */
    private boolean digestExists(String kind, String period, String practiceUuid) {
        Number count = (Number) em.createNativeQuery(
                        "SELECT COUNT(*) FROM recruitment_events "
                        + "WHERE event_type = 'AI_DIGEST_GENERATED' "
                        + "AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.kind')) = :kind "
                        + "AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.period')) = :period "
                        + "AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(payload, '$.practice_uuid')), '') "
                        + "    = :practice")
                .setParameter("kind", kind)
                .setParameter("period", period)
                .setParameter("practice", practiceUuid == null ? "" : practiceUuid)
                .getSingleResult();
        return count.longValue() > 0;
    }

    // ------------------------------------------------------------------
    // Projection reads (the digests' sole aggregate input — plan §P24)
    // ------------------------------------------------------------------

    /**
     * Load the funnel digest's two windows.
     *
     * <p>The reported period is the ISO week beginning {@code weekMonday},
     * read at week grain from {@code recruitment_fact_weekly} (V523) — the
     * week the message is titled with is now the week the message counts.
     * The preceding week is loaded in the same shape so every headline
     * number can carry a delta. The month series is loaded separately at
     * month grain purely as trend context for the chart, and is never
     * summed into a headline figure.</p>
     */
    private AiDigestFacts loadWeeklyFacts(LocalDate weekMonday, YearMonth trendFrom,
                                          YearMonth trendTo, String practiceUuid) {
        AiDigestFacts.FunnelWindow week = loadFunnelWindow(weekMonday, practiceUuid);
        AiDigestFacts.FunnelWindow previous =
                loadFunnelWindow(weekMonday.minusWeeks(1), practiceUuid);

        String scope = practiceScope(practiceUuid);
        LocalDate tf = trendFrom.atDay(1);
        LocalDate tt = trendTo.atDay(1);

        List<AiDigestFacts.MonthCount> trend = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT DATE_FORMAT(month, '%%Y-%%m'), SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'APPLICATION_CREATED' AND month BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 1
                """.formatted(scope), tf, tt, practiceUuid)) {
            trend.add(new AiDigestFacts.MonthCount((String) row[0], longOf(row[1])));
        }

        // Current state, not a flow: bare counts from the positions table
        // (the one sanctioned non-projection input — AiDigestFacts javadoc).
        List<AiDigestFacts.CodeCount> openPositions = new ArrayList<>();
        var openQuery = em.createNativeQuery(
                "SELECT hiring_track, COUNT(*) FROM recruitment_positions WHERE status = 'OPEN'"
                        + (practiceUuid == null ? ""
                                : " AND hiring_track <> 'PARTNER' AND practice_uuid = :practice")
                        + " GROUP BY 1 ORDER BY 1");
        if (practiceUuid != null) {
            openQuery.setParameter("practice", practiceUuid);
        }
        for (Object row : openQuery.getResultList()) {
            Object[] cols = (Object[]) row;
            openPositions.add(new AiDigestFacts.CodeCount((String) cols[0], longOf(cols[1])));
        }

        return new AiDigestFacts(trendFrom.toString(), trendTo.toString(),
                new AiDigestFacts.WeeklyFunnel(week, previous, trend, openPositions),
                null);
    }

    /**
     * One ISO week of funnel flow from the week-grain projection. Both
     * bounds are the same Monday: {@code recruitment_fact_weekly} stores
     * one row per (week × fact × dims), so a single week is an equality
     * match expressed through the shared {@code BETWEEN} helper.
     */
    private AiDigestFacts.FunnelWindow loadFunnelWindow(LocalDate weekMonday, String practiceUuid) {
        String scope = practiceScope(practiceUuid);
        LocalDate f = weekMonday;
        LocalDate t = weekMonday;

        List<AiDigestFacts.CodeCount> applications = codeCounts("""
                SELECT source, SUM(cnt)
                FROM recruitment_fact_weekly
                WHERE fact = 'APPLICATION_CREATED' AND week BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 2 DESC, 1
                """.formatted(scope), f, t, practiceUuid);

        List<AiDigestFacts.StageMove> stageMoves = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT stage_from, stage_to, outcome, SUM(cnt)
                FROM recruitment_fact_weekly
                WHERE fact = 'STAGE_MOVED' AND week BETWEEN :f AND :t%s
                GROUP BY 1, 2, 3 ORDER BY 1, 2, 3
                """.formatted(scope), f, t, practiceUuid)) {
            stageMoves.add(new AiDigestFacts.StageMove(
                    (String) row[0], (String) row[1], (String) row[2], longOf(row[3])));
        }

        List<AiDigestFacts.StageDays> timeInStage = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT stage_from, SUM(sum_days), SUM(cnt)
                FROM recruitment_fact_weekly
                WHERE fact IN ('STAGE_MOVED', 'TERMINAL') AND stage_from <> ''
                  AND week BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 1
                """.formatted(scope), f, t, practiceUuid)) {
            long moves = longOf(row[2]);
            double avg = moves == 0 ? 0d : ((Number) row[1]).doubleValue() / moves;
            timeInStage.add(new AiDigestFacts.StageDays((String) row[0], avg, moves));
        }

        List<AiDigestFacts.CodeCount> terminals = codeCounts("""
                SELECT outcome, SUM(cnt)
                FROM recruitment_fact_weekly
                WHERE fact = 'TERMINAL' AND week BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 1
                """.formatted(scope), f, t, practiceUuid);

        long hires = singleCount("""
                SELECT COALESCE(SUM(cnt), 0) FROM recruitment_fact_weekly
                WHERE fact = 'HIRED' AND week BETWEEN :f AND :t%s
                """.formatted(scope), f, t, practiceUuid);

        long scorecards = singleCount("""
                SELECT COALESCE(SUM(cnt), 0) FROM recruitment_fact_weekly
                WHERE fact = 'SCORECARD_SUBMITTED' AND week BETWEEN :f AND :t%s
                """.formatted(scope), f, t, practiceUuid);

        List<AiDigestFacts.CodeCount> nudges = codeCounts("""
                SELECT detail, SUM(cnt)
                FROM recruitment_fact_weekly
                WHERE fact = 'NUDGE_SENT' AND week BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 1
                """.formatted(scope), f, t, practiceUuid);

        return new AiDigestFacts.FunnelWindow(
                weekMonday.toString(), weekMonday.plusDays(6).toString(),
                applications, stageMoves, timeInStage, terminals,
                hires, scorecards, nudges);
    }

    /**
     * The practice dimension of a digest query. Company-wide digests read
     * everything; a per-practice digest is narrowed to that practice AND
     * excludes the partner track — a practice channel is a shared channel,
     * and confidential hiring never reaches one (Slack spec §5.2). Returns a
     * SQL fragment appended to the WHERE clause; the {@code :practice}
     * parameter is bound by {@link #rows}/{@link #codeCounts}/
     * {@link #singleCount}, never interpolated.
     */
    private static String practiceScope(String practiceUuid) {
        return practiceUuid == null ? ""
                : " AND practice_uuid = :practice AND hiring_track <> 'PARTNER'";
    }

    private AiDigestFacts loadRejectionFacts(YearMonth from, YearMonth to, String quarterLabel,
                                             String practiceUuid) {
        LocalDate f = from.atDay(1);
        LocalDate t = to.atDay(1);
        String scope = practiceScope(practiceUuid);

        List<AiDigestFacts.CodeCount> byReason = codeCounts("""
                SELECT detail, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 2 DESC
                """.formatted(scope), f, t, practiceUuid);

        List<AiDigestFacts.CodeCount> byStage = codeCounts("""
                SELECT stage_from, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t%s
                GROUP BY 1 ORDER BY 2 DESC
                """.formatted(scope), f, t, practiceUuid);

        Map<String, long[]> perSource = new LinkedHashMap<>(); // source -> [rejected, applications]
        for (Object[] row : rows("""
                SELECT source, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t%s
                GROUP BY 1
                """.formatted(scope), f, t, practiceUuid)) {
            perSource.computeIfAbsent(emptyToUnknown((String) row[0]), k -> new long[2])[0]
                    += longOf(row[1]);
        }
        for (Object[] row : rows("""
                SELECT source, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'APPLICATION_CREATED' AND month BETWEEN :f AND :t%s
                GROUP BY 1
                """.formatted(scope), f, t, practiceUuid)) {
            perSource.computeIfAbsent(emptyToUnknown((String) row[0]), k -> new long[2])[1]
                    += longOf(row[1]);
        }
        List<AiDigestFacts.SourceRejectionRate> bySource = perSource.entrySet().stream()
                .map(e -> new AiDigestFacts.SourceRejectionRate(
                        e.getKey(), e.getValue()[0], e.getValue()[1]))
                .toList();

        long totalRejections = byReason.stream().mapToLong(AiDigestFacts.CodeCount::count).sum();
        long totalApplications = perSource.values().stream().mapToLong(c -> c[1]).sum();

        return new AiDigestFacts(from.toString(), to.toString(), null,
                new AiDigestFacts.RejectionPatterns(quarterLabel, byReason, byStage,
                        bySource, totalRejections, totalApplications));
    }

    // ------------------------------------------------------------------
    // Model round-trip (no transaction, store=false)
    // ------------------------------------------------------------------

    /** Returns the sanitized narrative, or null on refusal/failure (logged, no event). */
    private String callModel(String systemPrompt, String userPrompt, String kind, String period) {
        String raw = openAIService.generatePlainText(systemPrompt, userPrompt,
                digestModel, MAX_OUTPUT_TOKENS, TEMPERATURE, false);
        String narrative = sanitizeNarrative(raw);
        if (narrative == null) {
            log.warnf("AI digest %s (%s): model returned no usable output — "
                    + "no event appended, the next run retries", kind, period);
        }
        return narrative;
    }

    /**
     * The digest event (plan §P24): narrative and KPIs in {@code payload} —
     * aggregates only, deliberately NOT {@code pii}, so digests survive
     * anonymization sweeps. {@code candidate_uuid} NULL, no pii section
     * ⇒ {@code pii_state=NONE} by the recorder.
     */
    private void appendDigestEvent(String kind, String period, AiDigestFacts facts,
                                   String narrative, Map<String, Object> kpis,
                                   String practiceUuid) {
        RecruitmentEventBuilder builder = RecruitmentEventBuilder
                .event(RecruitmentEventType.AI_DIGEST_GENERATED)
                .actorScheduler()
                .payload("kind", kind)
                .payload("period", period);
        if (practiceUuid != null) {
            // Present ⇒ this is a practice edition; the renderer routes it to
            // that practice's channel instead of the HR channel.
            builder = builder.payload("practice_uuid", practiceUuid);
        }
        builder = builder
                .payload("window_from", facts.windowFrom())
                .payload("window_to", facts.windowTo())
                .payload("model", digestModel)
                .payload("prompt_version", AiDigestPrompts.PROMPT_VERSION)
                .payload("narrative", narrative)
                .payload("kpis", kpis);
        if (facts.weeklyFunnel() != null) {
            // Everything the Slack renderer needs to build its table and
            // chart WITHOUT re-querying — a second independent count is
            // exactly how the old digest ended up contradicting itself.
            builder = builder
                    .payload("week_from", facts.weeklyFunnel().week().from())
                    .payload("week_to", facts.weeklyFunnel().week().to())
                    .payload("funnel", funnelRows(facts.weeklyFunnel()))
                    .payload("sources", codeRows(facts.weeklyFunnel().week().applicationsBySource()))
                    .payload("open_positions_by_track",
                            codeRows(facts.weeklyFunnel().openPositionsByTrack()))
                    .payload("trend", facts.weeklyFunnel().monthlyApplications().stream()
                            .map(m -> Map.<String, Object>of(
                                    "month", m.month(), "count", m.count()))
                            .toList());
        }
        eventRecorder.record(builder);
    }

    /**
     * The funnel table's rows: one per stage transition seen this week,
     * already carrying the Danish labels, the average days on the stage
     * being left, and the week-over-week delta. Built here rather than in
     * the renderer so the numbers in the message and the numbers the model
     * was shown come from one computation.
     */
    private static List<Map<String, Object>> funnelRows(AiDigestFacts.WeeklyFunnel funnel) {
        Map<String, Long> previous = new LinkedHashMap<>();
        for (AiDigestFacts.StageMove move : funnel.previousWeek().stageMoves()) {
            previous.merge(move.fromStage() + ">" + move.toStage(), move.count(), Long::sum);
        }
        Map<String, Double> avgDays = new LinkedHashMap<>();
        for (AiDigestFacts.StageDays days : funnel.week().timeInStage()) {
            avgDays.put(days.stage(), days.avgDays());
        }
        List<Map<String, Object>> rows = new ArrayList<>();
        for (AiDigestFacts.StageMove move : funnel.week().stageMoves()) {
            String key = move.fromStage() + ">" + move.toStage();
            Map<String, Object> row = new LinkedHashMap<>();
            row.put("from", RecruitmentDanishLabels.label(move.fromStage()));
            row.put("to", RecruitmentDanishLabels.label(move.toStage()));
            row.put("count", move.count());
            row.put("delta", move.count() - previous.getOrDefault(key, 0L));
            Double avg = avgDays.get(move.fromStage());
            row.put("avg_days", avg == null ? null : Math.round(avg * 10d) / 10d);
            rows.add(row);
        }
        return rows;
    }

    /** {@code [{label, count}]} with codes already translated to Danish. */
    private static List<Map<String, Object>> codeRows(List<AiDigestFacts.CodeCount> counts) {
        return counts.stream()
                .map(c -> Map.<String, Object>of(
                        "label", RecruitmentDanishLabels.label(c.code()),
                        "count", c.count()))
                .toList();
    }

    /** Normalise newlines, strip control chars except newline, trim, cap. Blank ⇒ null. */
    static String sanitizeNarrative(String value) {
        if (value == null) {
            return null;
        }
        String cleaned = value.replace("\r\n", "\n").replace('\r', '\n')
                .replaceAll("[\\p{Cc}\\p{Cf}&&[^\\n]]", " ")
                .trim();
        if (cleaned.isEmpty()) {
            return null;
        }
        if (cleaned.length() > NARRATIVE_MAX_LENGTH) {
            cleaned = cleaned.substring(0, NARRATIVE_MAX_LENGTH).trim();
        }
        return cleaned;
    }

    // ------------------------------------------------------------------
    // Small helpers
    // ------------------------------------------------------------------

    private List<AiDigestFacts.CodeCount> codeCounts(String sql, LocalDate f, LocalDate t,
                                                     String practiceUuid) {
        List<AiDigestFacts.CodeCount> result = new ArrayList<>();
        for (Object[] row : rows(sql, f, t, practiceUuid)) {
            result.add(new AiDigestFacts.CodeCount(emptyToUnknown((String) row[0]), longOf(row[1])));
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    private List<Object[]> rows(String sql, LocalDate f, LocalDate t, String practiceUuid) {
        return scoped(sql, f, t, practiceUuid).getResultList();
    }

    private long singleCount(String sql, LocalDate f, LocalDate t, String practiceUuid) {
        return ((Number) scoped(sql, f, t, practiceUuid).getSingleResult()).longValue();
    }

    /** Window + optional practice binding — the one place {@code :practice} is bound. */
    private jakarta.persistence.Query scoped(String sql, LocalDate f, LocalDate t,
                                             String practiceUuid) {
        var query = em.createNativeQuery(sql)
                .setParameter("f", f)
                .setParameter("t", t);
        if (practiceUuid != null) {
            query.setParameter("practice", practiceUuid);
        }
        return query;
    }

    private static long longOf(Object value) {
        return ((Number) value).longValue();
    }

    /** The projection's '' sentinel rendered as a readable code. */
    private static String emptyToUnknown(String code) {
        return code == null || code.isEmpty() ? "UNKNOWN" : code;
    }

    /** Reads on batch threads need a transaction (lazily-bound EntityManager). */
    private <T> T inTx(java.util.function.Supplier<T> work) {
        return QuarkusTransaction.requiringNew().call(work::get);
    }

    /** Test seam — the config value the digests generate with. */
    public String model() {
        return digestModel;
    }
}
