package dk.trustworks.intranet.recruitmentservice.ai;

import dk.trustworks.intranet.apis.openai.OpenAIService;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventBuilder;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventRecorder;
import dk.trustworks.intranet.recruitmentservice.events.RecruitmentEventType;
import dk.trustworks.intranet.recruitmentservice.services.RecruitmentAiFeatureFlag;
import dk.trustworks.intranet.recruitmentservice.services.RecruitmentFeatureFlag;
import io.quarkus.narayana.jta.QuarkusTransaction;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import lombok.extern.jbosslog.JBossLog;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.ZoneId;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The two P24 AI digests (AI spec §5.5, plan §P24): the weekly funnel
 * narrative for the recruitment Slack channel and the quarterly
 * rejection-pattern narrative feeding direktionens sourcing report. This
 * service GENERATES a digest and appends {@code AI_DIGEST_GENERATED}; the
 * Slack posting is downstream ({@code SlackDigestRenderer} consumes the
 * event) — generation and delivery are decoupled exactly like every other
 * reactor moment.
 *
 * <h3>The PII boundary, three layers deep</h3>
 * Model input is exclusively the P20 reporting projection's aggregates
 * (plus bare open-position counts) carried by {@link AiDigestFacts} —
 * numbers and enum codes by type system; the projection's schema cannot
 * hold names; and the digest event stores its narrative in
 * {@code payload} (not {@code pii}) precisely BECAUSE it contains
 * aggregates only, so digests survive anonymization sweeps unchanged —
 * the one deliberate inversion of the pii rule (plan §P24, findings §P9).
 *
 * <h3>Cadence &amp; idempotency — self-healing clock</h3>
 * The digest batchlet runs DAILY; each digest decides for itself whether
 * its period needs generating (event-derived, the P17/P23 idiom):
 * <ul>
 *   <li><b>Weekly:</b> one digest per ISO week — generated by the first
 *       run of the week (normally Monday 06:30 UTC); a failed Monday run
 *       (OpenAI outage) retries Tuesday, keyed on the same week.</li>
 *   <li><b>Quarterly:</b> one digest per just-ended <em>fiscal</em>
 *       quarter (July→June year), generated within the first
 *       {@link #REJECTION_GRACE_DAYS} days of the new quarter. Enabling
 *       the toggle after the window ⇒ no retroactive digest (the
 *       companion specs' no-backfill rule).</li>
 * </ul>
 * Two instances racing on the same period (ECS cutover) can both
 * generate — at worst one duplicate digest, the morning-brief posture.
 *
 * <h3>Gating</h3>
 * {@code recruitment.pipeline.enabled} (the P22/P23 precedent — no side
 * surface leaks a dark module's activity) AND the digest's own
 * {@code recruitment.ai.digest.*} toggle, both read fresh per run.
 * OpenAI calls run with no transaction active and {@code store=false}
 * (the module's standing posture) — and the input is numbers anyway.
 */
@JBossLog
@ApplicationScoped
public class AiDigestService {

    /** payload.kind of the weekly funnel digest. */
    public static final String KIND_WEEKLY_FUNNEL = "WEEKLY_FUNNEL";

    /** payload.kind of the quarterly rejection-pattern digest. */
    public static final String KIND_REJECTION_PATTERNS = "REJECTION_PATTERNS";

    /** The quarterly digest generates only this many days into the new quarter. */
    static final int REJECTION_GRACE_DAYS = 14;

    /** Weekly window: the current month (month-to-date) plus this many full months back. */
    static final int WEEKLY_WINDOW_MONTHS_BACK = 3;

    /** Narratives are a short paragraph; cap the stored text defensively. */
    static final int NARRATIVE_MAX_LENGTH = 6000;

    /** ~4-8 Danish sentences; generous without letting a runaway response spin. */
    static final int MAX_OUTPUT_TOKENS = 900;

    /** Natural prose wants temperature (the P16 draft-model reasoning). */
    static final double TEMPERATURE = 0.7;

    /** The digest clock runs on the Copenhagen calendar (the P23 idiom). */
    public static final ZoneId COPENHAGEN = ZoneId.of("Europe/Copenhagen");

    /**
     * The digests reuse the P16 draft model config: both need a
     * temperature-capable model for natural Danish prose, and a second
     * config knob for the same requirement would just drift.
     */
    @ConfigProperty(name = "dk.trustworks.recruitment.ai.draft-model", defaultValue = "gpt-4o-mini")
    String digestModel;

    @Inject
    OpenAIService openAIService;

    @Inject
    RecruitmentFeatureFlag featureFlag;

    @Inject
    RecruitmentAiFeatureFlag aiFlags;

    @Inject
    RecruitmentEventRecorder eventRecorder;

    @Inject
    EntityManager em;

    /** Result of one digest attempt, for logs and the batchlet exit status. */
    public record DigestSummary(String kind, boolean enabled, boolean generated, String period) {

        @Override
        public String toString() {
            if (!enabled) {
                return kind + "[disabled]";
            }
            return kind + "[" + (generated ? "generated " : "up-to-date ") + period + "]";
        }
    }

    // ------------------------------------------------------------------
    // Weekly funnel narrative
    // ------------------------------------------------------------------

    /**
     * Generate this ISO week's funnel digest when it does not exist yet.
     * Safe to call daily and concurrently (class javadoc).
     */
    public DigestSummary runWeeklyFunnel() {
        return runWeeklyFunnel(LocalDate.now(COPENHAGEN));
    }

    /** Clock-injected variant — the batchlet passes today; tests pass fixed dates. */
    public DigestSummary runWeeklyFunnel(LocalDate today) {
        if (!inTx(featureFlag::isPipelineEnabled) || !inTx(aiFlags::isWeeklyFunnelDigestEnabled)) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, false, false, null);
        }
        String period = isoWeekKey(today);
        if (inTx(() -> digestExists(KIND_WEEKLY_FUNNEL, period))) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, true, false, period);
        }
        YearMonth windowTo = YearMonth.from(today);
        YearMonth windowFrom = windowTo.minusMonths(WEEKLY_WINDOW_MONTHS_BACK);
        AiDigestFacts facts = inTx(() -> loadWeeklyFacts(windowFrom, windowTo));

        String narrative = callModel(AiDigestPrompts.weeklySystemPrompt(),
                AiDigestPrompts.weeklyUserPrompt(facts), KIND_WEEKLY_FUNNEL, period);
        if (narrative == null) {
            return new DigestSummary(KIND_WEEKLY_FUNNEL, true, false, period);
        }

        Map<String, Object> kpis = new LinkedHashMap<>();
        kpis.put("applications", facts.weeklyFunnel().applicationsPerSource().stream()
                .mapToLong(AiDigestFacts.MonthCodeCount::count).sum());
        kpis.put("stage_moves", facts.weeklyFunnel().stageMoves().stream()
                .mapToLong(AiDigestFacts.StageMove::count).sum());
        kpis.put("terminals", facts.weeklyFunnel().terminalsByOutcome().stream()
                .mapToLong(AiDigestFacts.CodeCount::count).sum());
        kpis.put("hires", facts.weeklyFunnel().hires());
        kpis.put("scorecards", facts.weeklyFunnel().scorecardsSubmitted());
        kpis.put("nudges", facts.weeklyFunnel().nudgesByType().stream()
                .mapToLong(AiDigestFacts.CodeCount::count).sum());
        kpis.put("open_positions", facts.weeklyFunnel().openPositionsByTrack().stream()
                .mapToLong(AiDigestFacts.CodeCount::count).sum());

        inTx(() -> {
            appendDigestEvent(KIND_WEEKLY_FUNNEL, period, facts, narrative, kpis);
            return null;
        });
        log.infof("AI_DIGEST_GENERATED kind=%s period=%s model=%s",
                KIND_WEEKLY_FUNNEL, period, digestModel);
        return new DigestSummary(KIND_WEEKLY_FUNNEL, true, true, period);
    }

    // ------------------------------------------------------------------
    // Quarterly rejection patterns
    // ------------------------------------------------------------------

    /**
     * Generate the just-ended fiscal quarter's rejection digest when
     * inside the grace window and not generated yet.
     */
    public DigestSummary runRejectionPatterns() {
        return runRejectionPatterns(LocalDate.now(COPENHAGEN));
    }

    /** Clock-injected variant — the batchlet passes today; tests pass fixed dates. */
    public DigestSummary runRejectionPatterns(LocalDate today) {
        if (!inTx(featureFlag::isPipelineEnabled) || !inTx(aiFlags::isRejectionPatternsDigestEnabled)) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, false, false, null);
        }
        YearMonth quarterStart = fiscalQuarterStart(YearMonth.from(today));
        if (today.isAfter(quarterStart.atDay(1).plusDays(REJECTION_GRACE_DAYS - 1L))) {
            // Outside the window — the ended quarter's digest either exists
            // or was deliberately never generated (no retroactive backfill).
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, null);
        }
        YearMonth windowFrom = quarterStart.minusMonths(3);
        YearMonth windowTo = quarterStart.minusMonths(1);
        String period = fiscalQuarterLabel(windowFrom);
        if (inTx(() -> digestExists(KIND_REJECTION_PATTERNS, period))) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, period);
        }
        AiDigestFacts facts = inTx(() -> loadRejectionFacts(windowFrom, windowTo, period));

        String narrative = callModel(AiDigestPrompts.rejectionSystemPrompt(),
                AiDigestPrompts.rejectionUserPrompt(facts), KIND_REJECTION_PATTERNS, period);
        if (narrative == null) {
            return new DigestSummary(KIND_REJECTION_PATTERNS, true, false, period);
        }

        Map<String, Object> kpis = new LinkedHashMap<>();
        kpis.put("rejections", facts.rejectionPatterns().totalRejections());
        kpis.put("applications", facts.rejectionPatterns().totalApplications());

        inTx(() -> {
            appendDigestEvent(KIND_REJECTION_PATTERNS, period, facts, narrative, kpis);
            return null;
        });
        log.infof("AI_DIGEST_GENERATED kind=%s period=%s model=%s",
                KIND_REJECTION_PATTERNS, period, digestModel);
        return new DigestSummary(KIND_REJECTION_PATTERNS, true, true, period);
    }

    // ------------------------------------------------------------------
    // Period keys (fiscal year July→June — docs/finalized/shared/fiscal-year.md)
    // ------------------------------------------------------------------

    /** ISO week key, e.g. {@code 2026-W30} (week-based year). Shared with the DPO digest. */
    public static String isoWeekKey(LocalDate date) {
        int week = date.get(WeekFields.ISO.weekOfWeekBasedYear());
        int year = date.get(WeekFields.ISO.weekBasedYear());
        return "%d-W%02d".formatted(year, week);
    }

    /** First month of the fiscal quarter containing the given month (Jul/Oct/Jan/Apr). */
    static YearMonth fiscalQuarterStart(YearMonth month) {
        int offset = (month.getMonthValue() - 7 + 12) % 3;
        return month.minusMonths(offset);
    }

    /**
     * Fiscal-quarter period key of the quarter STARTING at the given month,
     * e.g. {@code 2026-04} → {@code FY2025/26-Q4}.
     */
    static String fiscalQuarterLabel(YearMonth quarterStart) {
        int m = quarterStart.getMonthValue();
        int fyStartYear = m >= 7 ? quarterStart.getYear() : quarterStart.getYear() - 1;
        int quarter = switch (m) {
            case 7 -> 1;
            case 10 -> 2;
            case 1 -> 3;
            case 4 -> 4;
            default -> throw new IllegalArgumentException(
                    quarterStart + " is not a fiscal quarter start");
        };
        return "FY%d/%02d-Q%d".formatted(fyStartYear, (fyStartYear + 1) % 100, quarter);
    }

    // ------------------------------------------------------------------
    // Idempotency (event-derived)
    // ------------------------------------------------------------------

    private boolean digestExists(String kind, String period) {
        Number count = (Number) em.createNativeQuery(
                        "SELECT COUNT(*) FROM recruitment_events "
                        + "WHERE event_type = 'AI_DIGEST_GENERATED' "
                        + "AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.kind')) = :kind "
                        + "AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.period')) = :period")
                .setParameter("kind", kind)
                .setParameter("period", period)
                .getSingleResult();
        return count.longValue() > 0;
    }

    // ------------------------------------------------------------------
    // Projection reads (the digests' sole aggregate input — plan §P24)
    // ------------------------------------------------------------------

    private AiDigestFacts loadWeeklyFacts(YearMonth from, YearMonth to) {
        LocalDate f = from.atDay(1);
        LocalDate t = to.atDay(1);

        List<AiDigestFacts.MonthCodeCount> applications = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT DATE_FORMAT(month, '%Y-%m'), source, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'APPLICATION_CREATED' AND month BETWEEN :f AND :t
                GROUP BY 1, 2 ORDER BY 1, 2
                """, f, t)) {
            applications.add(new AiDigestFacts.MonthCodeCount(
                    (String) row[0], emptyToUnknown((String) row[1]), longOf(row[2])));
        }

        List<AiDigestFacts.StageMove> stageMoves = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT stage_from, stage_to, outcome, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'STAGE_MOVED' AND month BETWEEN :f AND :t
                GROUP BY 1, 2, 3 ORDER BY 1, 2, 3
                """, f, t)) {
            stageMoves.add(new AiDigestFacts.StageMove(
                    (String) row[0], (String) row[1], (String) row[2], longOf(row[3])));
        }

        List<AiDigestFacts.StageDays> timeInStage = new ArrayList<>();
        for (Object[] row : rows("""
                SELECT stage_from, SUM(sum_days), SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact IN ('STAGE_MOVED', 'TERMINAL') AND stage_from <> '' AND month BETWEEN :f AND :t
                GROUP BY 1 ORDER BY 1
                """, f, t)) {
            long moves = longOf(row[2]);
            double avg = moves == 0 ? 0d : ((Number) row[1]).doubleValue() / moves;
            timeInStage.add(new AiDigestFacts.StageDays((String) row[0], avg, moves));
        }

        List<AiDigestFacts.CodeCount> terminals = codeCounts("""
                SELECT outcome, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND month BETWEEN :f AND :t
                GROUP BY 1 ORDER BY 1
                """, f, t);

        long hires = singleCount("""
                SELECT COALESCE(SUM(cnt), 0) FROM recruitment_fact_monthly
                WHERE fact = 'HIRED' AND month BETWEEN :f AND :t
                """, f, t);

        long scorecards = singleCount("""
                SELECT COALESCE(SUM(cnt), 0) FROM recruitment_fact_monthly
                WHERE fact = 'SCORECARD_SUBMITTED' AND month BETWEEN :f AND :t
                """, f, t);

        List<AiDigestFacts.CodeCount> nudges = codeCounts("""
                SELECT detail, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'NUDGE_SENT' AND month BETWEEN :f AND :t
                GROUP BY 1 ORDER BY 1
                """, f, t);

        // Current state, not a flow: bare counts from the positions table
        // (the one sanctioned non-projection input — AiDigestFacts javadoc).
        List<AiDigestFacts.CodeCount> openPositions = new ArrayList<>();
        for (Object row : em.createNativeQuery(
                        "SELECT hiring_track, COUNT(*) FROM recruitment_positions "
                        + "WHERE status = 'OPEN' GROUP BY 1 ORDER BY 1")
                .getResultList()) {
            Object[] cols = (Object[]) row;
            openPositions.add(new AiDigestFacts.CodeCount((String) cols[0], longOf(cols[1])));
        }

        return new AiDigestFacts(from.toString(), to.toString(),
                new AiDigestFacts.WeeklyFunnel(applications, stageMoves, timeInStage,
                        terminals, hires, scorecards, nudges, openPositions),
                null);
    }

    private AiDigestFacts loadRejectionFacts(YearMonth from, YearMonth to, String quarterLabel) {
        LocalDate f = from.atDay(1);
        LocalDate t = to.atDay(1);

        List<AiDigestFacts.CodeCount> byReason = codeCounts("""
                SELECT detail, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t
                GROUP BY 1 ORDER BY 2 DESC
                """, f, t);

        List<AiDigestFacts.CodeCount> byStage = codeCounts("""
                SELECT stage_from, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t
                GROUP BY 1 ORDER BY 2 DESC
                """, f, t);

        Map<String, long[]> perSource = new LinkedHashMap<>(); // source -> [rejected, applications]
        for (Object[] row : rows("""
                SELECT source, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'TERMINAL' AND outcome = 'REJECTED' AND month BETWEEN :f AND :t
                GROUP BY 1
                """, f, t)) {
            perSource.computeIfAbsent(emptyToUnknown((String) row[0]), k -> new long[2])[0]
                    += longOf(row[1]);
        }
        for (Object[] row : rows("""
                SELECT source, SUM(cnt)
                FROM recruitment_fact_monthly
                WHERE fact = 'APPLICATION_CREATED' AND month BETWEEN :f AND :t
                GROUP BY 1
                """, f, t)) {
            perSource.computeIfAbsent(emptyToUnknown((String) row[0]), k -> new long[2])[1]
                    += longOf(row[1]);
        }
        List<AiDigestFacts.SourceRejectionRate> bySource = perSource.entrySet().stream()
                .map(e -> new AiDigestFacts.SourceRejectionRate(
                        e.getKey(), e.getValue()[0], e.getValue()[1]))
                .toList();

        long totalRejections = byReason.stream().mapToLong(AiDigestFacts.CodeCount::count).sum();
        long totalApplications = perSource.values().stream().mapToLong(c -> c[1]).sum();

        return new AiDigestFacts(from.toString(), to.toString(), null,
                new AiDigestFacts.RejectionPatterns(quarterLabel, byReason, byStage,
                        bySource, totalRejections, totalApplications));
    }

    // ------------------------------------------------------------------
    // Model round-trip (no transaction, store=false)
    // ------------------------------------------------------------------

    /** Returns the sanitized narrative, or null on refusal/failure (logged, no event). */
    private String callModel(String systemPrompt, String userPrompt, String kind, String period) {
        String raw = openAIService.generatePlainText(systemPrompt, userPrompt,
                digestModel, MAX_OUTPUT_TOKENS, TEMPERATURE, false);
        String narrative = sanitizeNarrative(raw);
        if (narrative == null) {
            log.warnf("AI digest %s (%s): model returned no usable output — "
                    + "no event appended, the next run retries", kind, period);
        }
        return narrative;
    }

    /**
     * The digest event (plan §P24): narrative and KPIs in {@code payload} —
     * aggregates only, deliberately NOT {@code pii}, so digests survive
     * anonymization sweeps. {@code candidate_uuid} NULL, no pii section
     * ⇒ {@code pii_state=NONE} by the recorder.
     */
    private void appendDigestEvent(String kind, String period, AiDigestFacts facts,
                                   String narrative, Map<String, Object> kpis) {
        eventRecorder.record(RecruitmentEventBuilder
                .event(RecruitmentEventType.AI_DIGEST_GENERATED)
                .actorScheduler()
                .payload("kind", kind)
                .payload("period", period)
                .payload("window_from", facts.windowFrom())
                .payload("window_to", facts.windowTo())
                .payload("model", digestModel)
                .payload("prompt_version", AiDigestPrompts.PROMPT_VERSION)
                .payload("narrative", narrative)
                .payload("kpis", kpis));
    }

    /** Normalise newlines, strip control chars except newline, trim, cap. Blank ⇒ null. */
    static String sanitizeNarrative(String value) {
        if (value == null) {
            return null;
        }
        String cleaned = value.replace("\r\n", "\n").replace('\r', '\n')
                .replaceAll("[\\p{Cc}\\p{Cf}&&[^\\n]]", " ")
                .trim();
        if (cleaned.isEmpty()) {
            return null;
        }
        if (cleaned.length() > NARRATIVE_MAX_LENGTH) {
            cleaned = cleaned.substring(0, NARRATIVE_MAX_LENGTH).trim();
        }
        return cleaned;
    }

    // ------------------------------------------------------------------
    // Small helpers
    // ------------------------------------------------------------------

    private List<AiDigestFacts.CodeCount> codeCounts(String sql, LocalDate f, LocalDate t) {
        List<AiDigestFacts.CodeCount> result = new ArrayList<>();
        for (Object[] row : rows(sql, f, t)) {
            result.add(new AiDigestFacts.CodeCount(emptyToUnknown((String) row[0]), longOf(row[1])));
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    private List<Object[]> rows(String sql, LocalDate f, LocalDate t) {
        return em.createNativeQuery(sql)
                .setParameter("f", f)
                .setParameter("t", t)
                .getResultList();
    }

    private long singleCount(String sql, LocalDate f, LocalDate t) {
        return ((Number) em.createNativeQuery(sql)
                .setParameter("f", f)
                .setParameter("t", t)
                .getSingleResult()).longValue();
    }

    private static long longOf(Object value) {
        return ((Number) value).longValue();
    }

    /** The projection's '' sentinel rendered as a readable code. */
    private static String emptyToUnknown(String code) {
        return code == null || code.isEmpty() ? "UNKNOWN" : code;
    }

    /** Reads on batch threads need a transaction (lazily-bound EntityManager). */
    private <T> T inTx(java.util.function.Supplier<T> work) {
        return QuarkusTransaction.requiringNew().call(work::get);
    }

    /** Test seam — the config value the digests generate with. */
    public String model() {
        return digestModel;
    }
}
