version: "3.8"
services:
  intranet2.0:
    container_name: intranet2.0
    image: trustworks/intranet2.0:prod
    env_file:
      - docker-env-intranet.env
    ports:
      - "9000:8085"
    networks:
      - frontend
      - services
    depends_on:
      - twservices
  intranet:
    container_name: intranet
    image: trustworks/intranet:prod
    env_file:
      - docker-env-intranet.env
    ports:
      - "80:8085"
    networks:
      - frontend
      - services
    depends_on:
      - twservices
  twservices:
    container_name: twservices
    image: trustworks/twservices:prod
    env_file:
      - docker-env-twservices.env
      - userpass.env
      - aws.env
    ports:
      - "9093:9093"
    networks:
      - services
      - backend
networks:
  frontend:
  backend:
  services:
    external:
      name: services_network


