package dk.trustworks.intranet.aggregates.invoice.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import dk.trustworks.intranet.aggregates.invoice.model.enums.InvoiceItemOrigin;
import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * Created by hans on 08/07/2017.
 */
@Getter
@Setter
@Entity
@Table(name = "invoiceitems")
public class InvoiceItem extends PanacheEntityBase {

    @Id
    @EqualsAndHashCode.Include
    public String uuid;
    public String consultantuuid;
    public String itemname;
    public String description;
    public double rate;
    public double hours;
    public int position;
    @JsonIgnore
    public String invoiceuuid;

    @Enumerated(jakarta.persistence.EnumType.STRING)
    @Column(name = "origin")
    public InvoiceItemOrigin origin = InvoiceItemOrigin.BASE;

    @Column(name = "calculation_ref")
    public String calculationRef;

    @Column(name = "rule_id")
    public String ruleId;

    @Column(name = "label")
    public String label;

    /**
     * Points to {@code invoiceitems.uuid} on the source invoice this line was derived from.
     * Populated on internal-invoice lines generated by {@code InternalInvoiceLineGenerator}
     * (attribution-driven flow, V300+). NULL on non-internal items and on legacy internal
     * items created before V300.
     */
    @Column(name = "source_item_uuid")
    public String sourceItemUuid;

    /**
     * Points to {@code invoice_item_attributions.uuid} this line represents. Populated on
     * every internal-invoice line generated under the attribution-driven flow — one line
     * equals one attribution row. NULL on non-internal items and on legacy (pre-V300)
     * internal items.
     */
    @Column(name = "source_attribution_uuid")
    public String sourceAttributionUuid;

    public InvoiceItem() {
        if( this.uuid == null ) {
            this.uuid = UUID.randomUUID().toString();
        }
    }

    public InvoiceItem(String itemname, String description, double rate, double hours, String invoiceuuid) {
        uuid = UUID.randomUUID().toString();
        this.itemname = itemname;
        this.description = description;
        this.rate = rate;
        this.hours = hours;
        this.invoiceuuid = invoiceuuid;
    }

    public InvoiceItem(String useruuid, String itemname, String description, double rate, double hours, int position, String invoiceuuid) {
        this(itemname, description, rate, hours, invoiceuuid);
        this.consultantuuid = useruuid;
        this.position = position;
    }

    public InvoiceItem(String useruuid, String itemname, String description, double rate, double hours, int position, String invoiceuuid, InvoiceItemOrigin origin) {
        this(useruuid, itemname, description, rate, hours, position, invoiceuuid);
        this.origin = origin;
    }

    /**
     * Copy-constructor that preserves an existing UUID.
     * Falls back to a random UUID when {@code existingUuid} is null or blank.
     */
    public InvoiceItem(String existingUuid, String useruuid, String itemname,
                       String description, double rate, double hours,
                       int position, String invoiceuuid, InvoiceItemOrigin origin) {
        this.uuid = (existingUuid != null && !existingUuid.isBlank())
                    ? existingUuid : UUID.randomUUID().toString();
        this.consultantuuid = useruuid;
        this.itemname = itemname;
        this.description = description;
        this.rate = rate;
        this.hours = hours;
        this.position = position;
        this.invoiceuuid = invoiceuuid;
        this.origin = origin;
    }

    @Override
    public String toString() {
        return "InvoiceItem{" +
                "uuid='" + uuid + '\'' +
                ", itemname='" + itemname + '\'' +
                ", rate=" + rate +
                ", hours=" + hours +
                ", origin=" + origin +
                '}';
    }
}