package dk.trustworks.intranet.aggregates.forecast.services;

import dk.trustworks.intranet.aggregates.forecast.dto.cxo.RevenueForecastBandMonthDTO;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Service-level tests for {@link CxoForecastService#revenueForecast(Set)}
 * mirroring the BFF route at {@code /api/cxo/forecast/revenue-forecast}.
 *
 * <p>Unlike the other CXO endpoints, the time series is generated by walking
 * a Java cursor across (trailing 6 + current + 12 forward) = 19 months. The
 * result therefore always contains 19 entries even when the underlying tables
 * are empty — so the company-filter test asserts {@code size == 19} (with all
 * forecast values 0) instead of {@code isEmpty()}.</p>
 *
 * <p>The shape test asserts row-level invariants: month format, finite
 * numeric values, and that the {@code forecastLow <= forecastMid <=
 * forecastHigh} layering holds.</p>
 */
@QuarkusTest
class CxoForecastServiceRevenueForecastTest {

    private static final int EXPECTED_MONTHS = 19;

    @Inject
    CxoForecastService service;

    @Test
    void revenueForecast_noFilter_returnsValidShape() {
        List<RevenueForecastBandMonthDTO> result = service.revenueForecast(null);
        assertNotNull(result);
        assertEquals(EXPECTED_MONTHS, result.size(),
                "Time series window is trailing 6 + current + 12 forward = 19 months");
        for (RevenueForecastBandMonthDTO m : result) {
            assertNotNull(m.month(), "month must not be null");
            assertTrue(m.month().matches("\\d{6}"), "month must be YYYYMM: " + m.month());
            assertNotNull(m.monthLabel(), "monthLabel must not be null");
            // actualRevenueDkk is intentionally nullable — check finite when present
            if (m.actualRevenueDkk() != null) {
                assertTrue(Double.isFinite(m.actualRevenueDkk().doubleValue()),
                        "actualRevenueDkk must be finite when present");
            }
            assertTrue(Double.isFinite(m.budgetDkk()), "budgetDkk must be finite");
            assertTrue(Double.isFinite(m.forecastLowDkk()), "forecastLowDkk must be finite");
            assertTrue(Double.isFinite(m.forecastMidDkk()), "forecastMidDkk must be finite");
            assertTrue(Double.isFinite(m.forecastHighDkk()), "forecastHighDkk must be finite");
            // SQL parity invariant: low = backlog, mid = backlog + pipeline,
            // high = backlog + pipeline + renewal. Pipeline and renewal are
            // non-negative, so low <= mid <= high is required by construction.
            assertTrue(m.forecastLowDkk() <= m.forecastMidDkk() + 1e-6
                            && m.forecastMidDkk() <= m.forecastHighDkk() + 1e-6,
                    "Band ordering forecastLow <= forecastMid <= forecastHigh must hold");
        }
    }

    @Test
    void revenueForecast_withCompanyFilter_returnsAllZeroWindow() {
        Set<String> randomUuids = Set.of(
                "00000000-0000-0000-0000-000000000001",
                "00000000-0000-0000-0000-000000000002");
        List<RevenueForecastBandMonthDTO> result = service.revenueForecast(randomUuids);
        assertNotNull(result);
        assertEquals(EXPECTED_MONTHS, result.size(),
                "Time series is generated even when no underlying rows match — 19 zero-valued months");
        for (RevenueForecastBandMonthDTO m : result) {
            assertEquals(0.0, m.budgetDkk(), 1e-9, "budgetDkk must be zero for unmatched filter");
            assertEquals(0.0, m.forecastLowDkk(), 1e-9, "forecastLowDkk must be zero for unmatched filter");
            assertEquals(0.0, m.forecastMidDkk(), 1e-9, "forecastMidDkk must be zero for unmatched filter");
            assertEquals(0.0, m.forecastHighDkk(), 1e-9, "forecastHighDkk must be zero for unmatched filter");
        }
    }
}
