package dk.trustworks.intranet.aggregates.practices.dto.cxo;

public record PracticeContributionPeriodDTO(
        String startMonth,
        String endMonth,
        String sourceStatus,
        String sourceReason,
        String fxStatus,
        String fxReason,
        String attributionStatus,
        String attributionReason,
        String revenueAttributionMethod,
        int revenueRegisteredWorkValueAllocationCount,
        int revenueRegisteredHoursAllocationCount,
        int revenueScheduledCapacityFallbackAllocationCount,
        int revenueMonthEndPracticeFallbackAllocationCount,
        int costMonthEndPracticeFallbackEmployeeMonthCount,
        int historicalPracticeFallbackAllocationCount,
        boolean historicalPracticeFallbackUsed,
        String attributionExplanationCode,
        String attributionExplanation,
        String costCompletenessStatus,
        String costCompletenessReason,
        String fteCompletenessStatus,
        String fteCompletenessReason,
        int expectedFteCellCount,
        int coveredFteCellCount,
        int missingFteCellCount,
        String practiceBasisStatus,
        String practiceBasisReason,
        String contributionStatus,
        String availabilityReason,
        PracticeContributionEvidenceDTO evidence) {
}
