package dk.trustworks.intranet.recruitmentservice.ai;

import dk.trustworks.intranet.fileservice.model.File;
import dk.trustworks.intranet.fileservice.services.S3FileService;
import dk.trustworks.intranet.recruitmentservice.ai.CvContentExtractor.CvContent;
import dk.trustworks.intranet.recruitmentservice.resources.P8ProfileFixtures;
import io.quarkus.narayana.jta.QuarkusTransaction;
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * P9 §8.6: the CV extraction pipeline with fixture PDFs generated by
 * PDFBox in-test — text PDFs yield stripped text, image-only PDFs fall
 * back to a rendered page-1 PNG (never the raw PDF bytes), JPEG/PNG CVs
 * pass straight through, and the failure paths (no CV event, file-row
 * relateduuid mismatch) degrade to the answers-only empty result. S3 is
 * mocked; the {@code files} metadata row is real (the IDOR guard reads it
 * before any S3 round-trip).
 */
@QuarkusTest
class CvContentExtractorTest {

    @Inject
    EntityManager em;

    @Inject
    CvContentExtractor extractor;

    @InjectMock
    S3FileService s3FileService;

    private String candidateUuid;
    private String actorUser;

    @BeforeEach
    void seed() {
        candidateUuid = UUID.randomUUID().toString();
        actorUser = UUID.randomUUID().toString();
        QuarkusTransaction.requiringNew().run(() -> {
            P8ProfileFixtures.insertUser(em, actorUser, "Fia", "Fixture");
            P8ProfileFixtures.insertCandidate(em, candidateUuid,
                    "PII_SENTINEL Cv", "PII_SENTINEL Tester", "ACTIVE", null, null, actorUser);
        });
    }

    private final List<String> seededFileUuids = new java.util.ArrayList<>();

    @AfterEach
    void cleanup() {
        QuarkusTransaction.requiringNew().run(() -> {
            if (!seededFileUuids.isEmpty()) {
                // The mismatch fixture's row is related to ANOTHER uuid, so
                // the candidate-scoped cleanup would miss it.
                em.createNativeQuery("DELETE FROM files WHERE uuid IN :u")
                        .setParameter("u", List.copyOf(seededFileUuids)).executeUpdate();
            }
            P8ProfileFixtures.cleanupRecruitmentRows(em,
                    List.of(candidateUuid), List.of(), List.of(actorUser), null);
        });
        seededFileUuids.clear();
    }

    // ---- fixtures ----------------------------------------------------------------

    private String seedCvUpload(String contentType, byte[] bytes, String relatedUuid) {
        String fileUuid = UUID.randomUUID().toString();
        QuarkusTransaction.requiringNew().run(() -> {
            P8ProfileFixtures.insertFileRow(em, fileUuid, relatedUuid, "cv.bin");
            P8ProfileFixtures.insertEvent(em, "DOCUMENT_UPLOADED", candidateUuid, null, null,
                    "CANDIDATE", null, "NORMAL",
                    "{\"kind\":\"CV\",\"file_uuid\":\"" + fileUuid
                            + "\",\"content_type\":\"" + contentType + "\"}",
                    "{\"filename\":\"PII_SENTINEL-cv\"}");
        });
        when(s3FileService.findOne(fileUuid)).thenReturn(new File(
                fileUuid, relatedUuid, "DOCUMENT", "cv.bin", "cv.bin", LocalDate.now(), bytes));
        seededFileUuids.add(fileUuid);
        return fileUuid;
    }

    private static byte[] textPdf(String text) throws Exception {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);
            try (PDPageContentStream stream = new PDPageContentStream(document, page)) {
                stream.beginText();
                stream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 11);
                stream.newLineAtOffset(40, 700);
                // Split into lines — a content stream shows one line at a time.
                for (String line : text.split("\n")) {
                    stream.showText(line);
                    stream.newLineAtOffset(0, -14);
                }
                stream.endText();
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        }
    }

    private static byte[] blankPdf() throws Exception {
        try (PDDocument document = new PDDocument()) {
            document.addPage(new PDPage());
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        }
    }

    private static byte[] tinyPng() throws Exception {
        BufferedImage image = new BufferedImage(4, 4, BufferedImage.TYPE_INT_RGB);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ImageIO.write(image, "png", out);
        return out.toByteArray();
    }

    // ---- tests --------------------------------------------------------------------

    @Test
    void textPdf_yieldsStrippedText() throws Exception {
        String paragraph = ("Erfaren konsulent med otte aars erfaring inden for arkitektur. ").repeat(8);
        seedCvUpload("application/pdf", textPdf(paragraph), candidateUuid);

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.hasText(), "a text PDF must yield extracted text");
        assertFalse(content.hasImage());
        assertTrue(content.text().contains("Erfaren konsulent"));
    }

    @Test
    void imageOnlyPdf_fallsBackToRenderedPageOnePng_neverRawPdfBytes() throws Exception {
        seedCvUpload("application/pdf", blankPdf(), candidateUuid);

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.hasImage(), "an image-only PDF must fall back to the vision path");
        assertEquals("image/png", content.mimeType(), "the vision payload is a rendered PNG page");
        byte[] decoded = Base64.getDecoder().decode(content.base64Image());
        // PNG magic — proves it is the render, not the raw PDF (%PDF) bytes.
        assertEquals((byte) 0x89, decoded[0]);
        assertEquals('P', (char) decoded[1]);
        assertEquals('N', (char) decoded[2]);
        assertEquals('G', (char) decoded[3]);
    }

    @Test
    void imageCv_passesThroughAsIs() throws Exception {
        byte[] png = tinyPng();
        seedCvUpload("image/png", png, candidateUuid);

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.hasImage());
        assertEquals("image/png", content.mimeType());
        assertEquals(Base64.getEncoder().encodeToString(png), content.base64Image());
    }

    @Test
    void noCvEvent_returnsEmpty() {
        CvContent content = extractor.extract(candidateUuid);
        assertTrue(content.isEmpty(), "no CV upload ⇒ answers-only prompt");
        verify(s3FileService, never()).findOne(anyString());
    }

    @Test
    void relatedUuidMismatch_skipsWithoutTouchingS3() throws Exception {
        // The files row belongs to ANOTHER candidate — the IDOR-style guard
        // must refuse before any S3 round-trip.
        seedCvUpload("application/pdf", textPdf("Some other candidate's CV ".repeat(20)),
                UUID.randomUUID().toString());

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.isEmpty());
        verify(s3FileService, never()).findOne(anyString());
    }

    @Test
    void latestCvWins_highestSeqEvent() throws Exception {
        seedCvUpload("application/pdf", textPdf("OLD CV content ".repeat(30)), candidateUuid);
        seedCvUpload("application/pdf", textPdf("NEW CV content ".repeat(30)), candidateUuid);

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.hasText());
        assertTrue(content.text().contains("NEW CV content"),
                "the highest-seq CV upload is the one that counts");
    }

    @Test
    void mislabelledPdf_sniffedByMagicBytes_takesThePdfPathNotInputImage() throws Exception {
        // Declared image/png but actually a PDF — must never reach the
        // vision path as raw bytes (prod-bug posture, PR #178).
        seedCvUpload("image/png", textPdf("Mislabelled but real PDF text ".repeat(20)), candidateUuid);

        CvContent content = extractor.extract(candidateUuid);

        assertTrue(content.hasText(), "magic-byte sniff must route %PDF bytes through PDFBox");
        assertFalse(content.hasImage());
    }
}
