package dk.trustworks.intranet.messaging.emitters.enums;

public enum AggregateEventType {
    CREATE_CLIENT,
    CREATE_CONFERENCE_PARTICIPANT, UPDATE_CONFERENCE_PARTICIPANT, CHANGE_CONFERENCE_PARTICIPANT_PHASE,
    CREATE_USER, UPDATE_USER, CREATE_USER_STATUS, DELETE_USER_STATUS, CREATE_USER_SALARY, DELETE_USER_SALARY
}
