-- =============================================================================
-- V208: Create alert_dismissals table
-- =============================================================================
-- Purpose:
--   Persists per-user alert dismissals server-side, replacing the previous
--   localStorage-based approach in the AlertsCard dashboard component.
--
-- Design decisions:
--   - uuid (CHAR(36)): primary key, application-assigned UUID, consistent with
--     project UUID conventions.
--   - user_uuid (CHAR(36)): references the user who dismissed the alert. No FK
--     constraint to avoid coupling to the users table schema; validated at the
--     application layer.
--   - alert_id (VARCHAR(255)): opaque string key generated by generateAlerts()
--     in the BFF. Format is deterministic (e.g. "stale-contact::<clientUuid>"),
--     so the same alert dismissed today will still match on re-render.
--   - dismissed_at (DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP): stored in UTC,
--     displayed in local timezone by the client.
--   - UNIQUE on (user_uuid, alert_id): prevents duplicate dismissals; the
--     backend upsert can use INSERT IGNORE or ON DUPLICATE KEY UPDATE.
--   - Index on user_uuid: primary access pattern is "fetch all dismissals for
--     a given user", so this index is mandatory.
--
-- Rollback strategy:
--   DROP TABLE IF EXISTS alert_dismissals;
--   (No data backfill required — pre-existing localStorage dismissals are
--   abandoned; users will need to re-dismiss any previously dismissed alerts
--   once on the new version. Acceptable per product decision.)
--
-- Affected Quarkus entities/repositories:
--   - dk.trustworks.intranet.aggregates.crm.model.AlertDismissal  (to be created)
--   - dk.trustworks.intranet.aggregates.crm.resources.AlertDismissalResource (to be created)
--
-- =============================================================================

CREATE TABLE IF NOT EXISTS alert_dismissals (
    uuid         CHAR(36)     NOT NULL,
    user_uuid    CHAR(36)     NOT NULL,
    alert_id     VARCHAR(255) NOT NULL,
    dismissed_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_alert_dismissals        PRIMARY KEY (uuid),
    CONSTRAINT uq_alert_dismissals_user_alert UNIQUE (user_uuid, alert_id),
    INDEX idx_alert_dismissals_user_uuid (user_uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Validation queries (run after migration to verify correctness):
-- =============================================================================
-- 1. Confirm table and columns exist:
--    SHOW CREATE TABLE alert_dismissals;
--
-- 2. Confirm unique constraint prevents duplicates (expect error on 2nd insert):
--    INSERT INTO alert_dismissals (uuid, user_uuid, alert_id)
--        VALUES (UUID(), 'test-user-uuid', 'stale-contact::test-client');
--    INSERT INTO alert_dismissals (uuid, user_uuid, alert_id)
--        VALUES (UUID(), 'test-user-uuid', 'stale-contact::test-client');
--    -- ^ should fail with: Duplicate entry ... for key 'uq_alert_dismissals_user_alert'
--
-- 3. Confirm index is present:
--    SHOW INDEX FROM alert_dismissals;
--    -- Expect: idx_alert_dismissals_user_uuid on column user_uuid
--
-- 4. Confirm per-user lookup uses index (EXPLAIN output should show key=idx_alert_dismissals_user_uuid):
--    EXPLAIN SELECT uuid, alert_id FROM alert_dismissals WHERE user_uuid = 'test-user-uuid';
-- =============================================================================
