-- ============================================================================
-- V249: Create autofix_tasks table
-- ============================================================================
-- Purpose: Introduces the auto-fix task queue for the self-healing bug-fix
--          pipeline. Each row represents a request for Claude Code to analyze
--          a bug report and produce a draft pull request. Tasks are claimed
--          by a Fargate worker using SELECT ... FOR UPDATE, processed with
--          heartbeat-based lease management, and updated with results.
--
-- Spec reference:
--   - docs/specs/self-healing-app-phase-1a-infra-db.md, Section 3
--   - docs/specs/plans/phase-1a-infra-db-plan.md, Task 1.1
--
-- Changes:
--   1. Creates `autofix_tasks` table (task queue for Claude Code workers)
--   2. Adds 3 indexes for dispatcher poll, report lookup, and reaper queries
--
-- Backwards compatibility:
--   - No existing tables are modified
--   - No existing data is affected
--   - New table only; purely additive migration
--
-- Data semantics:
--   - task_id: CHAR(36) UUID generated by the Java application (UUID.randomUUID),
--     not by MariaDB UUID() which produces v1 UUIDs.
--   - status ENUM: PENDING (queued, awaiting worker), PROCESSING (worker claimed),
--     COMPLETED (PR created), FAILED (error after retries), CANCELLED (admin abort).
--   - heartbeat_at / lease_expires_at: DATETIME(3) with millisecond precision.
--     The worker updates heartbeat_at every 30 seconds; the reaper job checks
--     lease_expires_at to detect stuck/crashed workers.
--   - prompt: LONGTEXT containing the full structured prompt sent to Claude Code.
--     Includes SYSTEM_INSTRUCTIONS, SECURITY_RULES, and BUG_REPORT_EVIDENCE sections.
--   - result: LONGTEXT storing JSON output from Claude Code (root_cause,
--     files_changed, confidence, diff_scanner result, etc.).
--   - usage_info: LONGTEXT storing JSON with Anthropic API usage metrics
--     (tokens, cost, model used).
--   - metadata: LONGTEXT for extensible JSON metadata (future use).
--   - retry_count / max_retries: max_retries defaults to 2, meaning 3 total
--     attempts (initial + 2 retries). The worker increments retry_count on
--     transient failure and re-queues as PENDING if under the limit.
--   - requested_by: VARCHAR(100) stores either a user UUID (admin who clicked
--     "Request Auto-Fix") or a system actor identifier (e.g., "system:reaper").
--   - Timezone: created_at, started_at, completed_at store server-local time
--     via CURRENT_TIMESTAMP / application layer. Consistent with bug_reports.
--   - Nullability: prompt, repo_name are populated at creation. Fields like
--     pr_url, pr_number, result, error_message are populated during/after
--     processing. worker_id is set when a worker claims the task.
--
-- Rollback strategy:
--   DROP TABLE IF EXISTS autofix_tasks;
--
-- Impact:
--   - New Quarkus entity needed: AutoFixTask.java (or use native queries)
--   - New DTO: AutoFixTaskDTO.java
--   - New service methods in BugReportAutoFixService.java
--   - No existing entities or repositories are affected
--
-- Index rationale:
--   - idx_autofix_tasks_status_created: Dispatcher poll query
--     "SELECT ... WHERE status = 'PENDING' ORDER BY created_at ASC LIMIT 1 FOR UPDATE"
--   - idx_autofix_tasks_bug_report: Lookup tasks by bug report
--     "SELECT ... WHERE bug_report_uuid = ? ORDER BY created_at DESC"
--   - idx_autofix_tasks_lease_expires: Reaper job
--     "SELECT ... WHERE status = 'PROCESSING' AND lease_expires_at < NOW()"
--
-- Author: Claude Code
-- Date: 2026-03-17
-- ============================================================================

-- Step 1: Create the autofix_tasks table (task queue)
-- Each row is a unit of work for the Fargate Claude Code worker.
-- The worker claims tasks via SELECT ... FOR UPDATE on status = 'PENDING'.
CREATE TABLE autofix_tasks (
    task_id             CHAR(36)      NOT NULL
                        COMMENT 'Java-generated UUID v4 (not MariaDB UUID())',
    bug_report_uuid     CHAR(36)      NOT NULL
                        COMMENT 'FK to bug_reports.uuid — the report being fixed',
    status              ENUM('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED')
                                      NOT NULL DEFAULT 'PENDING'
                        COMMENT 'Task lifecycle state',
    prompt              LONGTEXT      NULL
                        COMMENT 'Full structured prompt sent to Claude Code (SYSTEM + SECURITY + EVIDENCE)',
    repo_name           VARCHAR(255)  NULL
                        COMMENT 'Target repository name (e.g., trustworks-intranet-v3, intranetservices)',
    branch_name         VARCHAR(255)  NULL
                        COMMENT 'Git branch created for the fix (e.g., autofix/bug-<uuid>)',
    pr_url              VARCHAR(500)  NULL
                        COMMENT 'GitHub draft PR URL after creation',
    pr_number           INT           NULL
                        COMMENT 'GitHub PR number',
    result              LONGTEXT      NULL
                        COMMENT 'JSON: Claude Code structured output (root_cause, files_changed, confidence, diff_scanner)',
    error_message       TEXT          NULL
                        COMMENT 'Error description if task failed',
    worker_id           VARCHAR(255)  NULL
                        COMMENT 'Fargate task ARN or container ID of the claiming worker',
    heartbeat_at        DATETIME(3)   NULL
                        COMMENT 'Last heartbeat from worker (millisecond precision). Updated every 30s.',
    lease_expires_at    DATETIME(3)   NULL
                        COMMENT 'Lease expiry time (millisecond precision). Reaper reclaims if past this.',
    retry_count         INT           NOT NULL DEFAULT 0
                        COMMENT 'Number of retry attempts so far',
    max_retries         INT           NOT NULL DEFAULT 2
                        COMMENT 'Maximum retries allowed (default 2 = 3 total attempts)',
    usage_info          LONGTEXT      NULL
                        COMMENT 'JSON: Anthropic API usage metrics (tokens, cost, model)',
    metadata            LONGTEXT      NULL
                        COMMENT 'JSON: extensible metadata for future use',
    requested_by        VARCHAR(100)  NULL
                        COMMENT 'UUID of admin who requested, or system actor identifier',
    created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
                        COMMENT 'Task creation timestamp (server-local time)',
    started_at          DATETIME      NULL
                        COMMENT 'When worker began processing',
    completed_at        DATETIME      NULL
                        COMMENT 'When task reached terminal state (COMPLETED/FAILED/CANCELLED)',

    PRIMARY KEY (task_id),

    CONSTRAINT fk_autofix_tasks_bug_report
        FOREIGN KEY (bug_report_uuid) REFERENCES bug_reports (uuid)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Step 2: Create indexes for common query patterns

-- Dispatcher poll: SELECT ... WHERE status = 'PENDING' ORDER BY created_at ASC LIMIT 1 FOR UPDATE
-- Composite index lets the query find the oldest pending task efficiently.
CREATE INDEX idx_autofix_tasks_status_created
    ON autofix_tasks (status, created_at);

-- Report lookup: SELECT ... WHERE bug_report_uuid = ? ORDER BY created_at DESC
-- Used by the admin dashboard to show task history for a bug report.
CREATE INDEX idx_autofix_tasks_bug_report
    ON autofix_tasks (bug_report_uuid);

-- Reaper job: SELECT ... WHERE status = 'PROCESSING' AND lease_expires_at < NOW()
-- Detects stuck/crashed workers whose lease has expired.
CREATE INDEX idx_autofix_tasks_lease_expires
    ON autofix_tasks (lease_expires_at);
